### PR TITLE
fixed documentation to explain the inclusion of raml-console element …

### PR DESCRIPTION
**Pull request by gianebao**
- Fixed documentation to explain the inclusion of `raml-console` element which should be `raml-console-loader`. 
- Remove `dist` to avoid unsynced and duplicate commits whenever there are changes.
- Simplified the use of options for `raml-console-loader` by allowing element attributes to be passed just like `raml-console`.

### CODE REVIEW

**Comment by CameronGo** [comment]
Hi, the documentation seems accurate as it relates to getting the inline functionality working with the src attribute, but passing in additional options like documentation-collapsed does not see to function.  Can you confirm if you observe the same behavior?

**Comment by gianebao** [comment]
i haven't tried documentation collapsed but disable-theme-switcher seems to work.

**Comment by CameronGo** [comment]
I tested that too and it isn't working for me.  My RAML loads now, but in this case the theme switcher is still displayed and functions.  Below is my full actual html file.  Am I misunderstanding how this needs to be used, or can you post what you are using?

```

<!doctype html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>API Console</title>
  <link href="styles/api-console-light-theme.css" rel="stylesheet" class="theme">
</head>
<body ng-app="ramlConsoleApp" ng-cloak class="raml-console-body">

  <raml-console-loader src="/PursuantHealthv1/api.raml" disable-theme-switcher></raml-console-loader>

  <script src="scripts/api-console-vendor.js"></script>
  <script src="scripts/api-console.js"></script>
  <script>
    $.noConflict();
  </script>
</body>
</html>
```

**Comment by gianebao** [comment]
Can you pull master again? i tried `documentation-collapsed` but apparently it's already collapsed by default so i use `resources-collapsed`.

Can I see your src/app/directives/raml-console-loader.js?

**Comment by CameronGo** [comment]
I re-pulled master, but that didn't seem to change anything.  My raml-console-loader.jr is below:

```
(function () {
  'use strict';

  angular.module('RAML.Directives')
    .directive('ramlConsoleLoader', function ramlConsoleLoader() {
      return {
        restrict:    'E',
        templateUrl: 'directives/raml-console-loader.tpl.html',
        replace:     true,
        controller:  'RamlConsoleLoaderController',
        scope:       {
          src:     '@',
          options: '='
        }
      };
    })
    .controller('RamlConsoleLoaderController', function RamlConsoleLoaderController(
      $scope,
      $window,
      ramlParser
    ) {
      $scope.vm = {
        error:   void(0),
        loaded:  false,
        options: $scope.options,
        raml:    void(0),
        src:     $scope.src
      };

      // ---

      (function activate() {
        loadFromUrl($scope.vm.src);
      })();

      // ---

      function loadFromUrl(url) {
        $scope.vm.raml   = void(0);
        $scope.vm.loaded = false;
        $scope.vm.error  = void(0);

        return ramlParser.loadPath($window.resolveUrl(url), null, $scope.options)
          .then(function (raml) {
            $scope.vm.raml = raml;
          })
          .catch(function (error) {
            $scope.vm.error = angular.extend(error, {
              /*jshint camelcase: false */
              buffer: (error.context_mark || error.problem_mark).buffer
              /*jshint camelcase: true */
            });
          })
          .finally(function () {
            $scope.vm.loaded = true;
          })
        ;
      }
    })
  ;
})();

```

**Pull request merged**
